name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: publish LaserCatEyes.Domain 
      id: publish_nuget_LaserCatEyes_Domain
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: LaserCatEyes.Domain/LaserCatEyes.Domain.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
    
    - name: publish LaserCatEyes.DataServiceSdk.DotNetStandard 
      id: publish_nuget_LaserCatEyes_DataServiceSdk_DotNetStandard
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: LaserCatEyes.DataServiceSdk.DotNetStandard/LaserCatEyes.DataServiceSdk.DotNetStandard.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
    
    - name: publish LaserCatEyes.HttpClientListener.DotNetStandard
      id: publish_nuget_LaserCatEyes_HttpClientListener_DotNetStandard
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: LaserCatEyes.HttpClientListener.DotNetStandard/LaserCatEyes.HttpClientListener.DotNetStandard.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
    
    - name: publish LaserCatEyes.DataServiceSdk 
      id: publish_nuget_LaserCatEyes_DataServiceSdk
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: LaserCatEyes.DataServiceSdk/LaserCatEyes.DataServiceSdk.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
    
    - name: publish LaserCatEyes.EndpointListener 
      id: publish_nuget_LaserCatEyes_EndpointListener
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: LaserCatEyes.EndpointListener/LaserCatEyes.EndpointListener.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}
    
    - name: publish LaserCatEyes.HttpClientListener 
      id: publish_nuget_LaserCatEyes_HttpClientListener
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: LaserCatEyes.HttpClientListener/LaserCatEyes.HttpClientListener.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}

    - name: publish LaserCatEyes.WCFListener 
      id: publish_nuget_LaserCatEyes_WCFListener
      uses: alirezanet/publish-nuget@v3.0.3
      with:
          PROJECT_FILE_PATH: LaserCatEyes.WCFListener/LaserCatEyes.WCFListener.csproj
          NUGET_KEY: ${{secrets.NUGET_KEY}}